version: "3.8"

services:
  database:
    container_name: database
    image: mysql
    environment: 
      - MYSQL_DATABASE=events
      - MYSQL_ROOT_PASSWORD=password
    networks: 
      - heroes-network
  service:
    container_name: service
    build: .
    restart: on-failure
    networks: 
      heroes-network:
        aliases: 
          - fight-of-heroes-service
networks: 
  heroes-network:
    name: heroes-network